/**
 * Regenerates ../wasmModuleRoots.ts from the release notes of
 * https://github.com/OffchainLabs/nitro/releases.
 *
 * Usage:
 *   yarn generate-wasm-module-roots
 *
 * Set GITHUB_TOKEN to avoid GitHub API rate limits (60 req/h unauthenticated).
 */
import * as fs from 'fs'
import * as path from 'path'

const RELEASES_URL =
  'https://api.github.com/repos/OffchainLabs/nitro/releases?per_page=100'
const OUTPUT_PATH = path.join(__dirname, '..', 'wasmModuleRoots.ts')

type GithubRelease = {
  tag_name: string
  body: string | null
  draft: boolean
}

// Minimal shape of the global fetch response; the repo tsconfig has no DOM lib.
type FetchResponse = {
  ok: boolean
  status: number
  statusText: string
  json(): Promise<unknown>
  headers: { get(name: string): string | null }
}
declare const fetch: (
  url: string,
  init?: { headers?: Record<string, string> }
) => Promise<FetchResponse>

type RootEntry = {
  consensusRelease: string
  maxArbosVersion: number
  arbosVersionSource: 'release-notes' | 'tag-major-fallback'
}

const fetchAllReleases = async (): Promise<GithubRelease[]> => {
  const releases: GithubRelease[] = []
  let url: string | null = RELEASES_URL

  while (url) {
    const headers: Record<string, string> = {
      accept: 'application/vnd.github+json',
    }
    if (process.env.GITHUB_TOKEN) {
      headers.authorization = `Bearer ${process.env.GITHUB_TOKEN}`
    }

    const response: FetchResponse = await fetch(url, { headers })
    if (!response.ok) {
      throw new Error(
        `GitHub API request failed: ${response.status} ${response.statusText}`
      )
    }
    releases.push(...((await response.json()) as GithubRelease[]))

    const linkHeader = response.headers.get('link') ?? ''
    const nextMatch = linkHeader.match(/<([^>]+)>;\s*rel="next"/)
    url = nextMatch ? nextMatch[1] : null
  }

  return releases
}

const isPrereleaseTag = (tag: string): boolean =>
  /-(rc|alpha|beta)|binary-release/.test(tag)

const extractEntries = (
  releases: GithubRelease[]
): Map<string, RootEntry[]> => {
  const rootToCandidates = new Map<string, RootEntry[]>()

  for (const release of releases) {
    const tag = release.tag_name
    if (release.draft || !tag.startsWith('consensus-')) continue

    const body = release.body ?? ''
    const rootMatch = body.match(/0x[0-9a-fA-F]{64}/)
    if (!rootMatch) {
      console.warn(`Skipping ${tag}: no WASM module root in release notes`)
      continue
    }
    const root = rootMatch[0].toLowerCase()

    const arbosMatch = body.match(/arbos (?:version )?(\d+)/i)
    const tagMajorMatch = tag.match(/^consensus-v(\d+)/)
    if (!arbosMatch && !tagMajorMatch) {
      console.warn(`Skipping ${tag}: cannot determine ArbOS version`)
      continue
    }

    const entry: RootEntry = arbosMatch
      ? {
          consensusRelease: tag,
          maxArbosVersion: Number(arbosMatch[1]),
          arbosVersionSource: 'release-notes',
        }
      : {
          consensusRelease: tag,
          // Release notes before consensus-v11 do not state an ArbOS version;
          // the consensus major number is used as an upper bound.
          maxArbosVersion: Number(tagMajorMatch![1]),
          arbosVersionSource: 'tag-major-fallback',
        }

    const candidates = rootToCandidates.get(root) ?? []
    candidates.push(entry)
    rootToCandidates.set(root, candidates)
  }

  return rootToCandidates
}

/** Several tags can publish the same root (e.g. a final release and its last rc); prefer the stable tag. */
const pickPreferred = (candidates: RootEntry[]): RootEntry => {
  const sorted = [...candidates].sort((a, b) => {
    const aPre = isPrereleaseTag(a.consensusRelease) ? 1 : 0
    const bPre = isPrereleaseTag(b.consensusRelease) ? 1 : 0
    if (aPre !== bPre) return aPre - bPre
    return a.consensusRelease.length - b.consensusRelease.length
  })
  return sorted[0]
}

const renderFile = (entries: [string, RootEntry][]): string => {
  const rows = entries
    .map(
      ([root, entry]) => `  '${root}': {
    consensusRelease: '${entry.consensusRelease}',
    maxArbosVersion: ${entry.maxArbosVersion},
  },`
    )
    .join('\n')

  return `// AUTO-GENERATED by scripts/generateWasmModuleRoots.ts — do not edit by hand.
// Regenerate with: yarn generate-wasm-module-roots

export type WasmModuleRootInfo = {
  consensusRelease: string
  /**
   * Highest ArbOS version supported by this consensus release. For releases
   * before consensus-v11 the release notes do not state an ArbOS version, so
   * the consensus major number is used as an upper bound — anything that old
   * is far below any modern minimum version anyway.
   */
  maxArbosVersion: number
}

/**
 * WASM module roots published in the release notes of
 * https://github.com/OffchainLabs/nitro/releases (tags prefixed \`consensus-\`).
 * Keys must be lowercase.
 */
export const KNOWN_WASM_MODULE_ROOTS: Record<string, WasmModuleRootInfo> = {
${rows}
}

export const getWasmModuleRootInfo = (
  wasmModuleRoot: string
): WasmModuleRootInfo | undefined =>
  KNOWN_WASM_MODULE_ROOTS[wasmModuleRoot.toLowerCase()]
`
}

const main = async () => {
  console.log('Fetching nitro releases from GitHub...')
  const releases = await fetchAllReleases()
  console.log(`Fetched ${releases.length} releases`)

  const rootToCandidates = extractEntries(releases)
  const entries: [string, RootEntry][] = [...rootToCandidates.entries()]
    .map(
      ([root, candidates]) =>
        [root, pickPreferred(candidates)] as [string, RootEntry]
    )
    .sort(
      ([, a], [, b]) =>
        a.maxArbosVersion - b.maxArbosVersion ||
        a.consensusRelease.localeCompare(b.consensusRelease)
    )

  const fallbacks = entries.filter(
    ([, e]) => e.arbosVersionSource === 'tag-major-fallback'
  )
  console.log(
    `Extracted ${entries.length} unique roots (${fallbacks.length} with ArbOS version inferred from the tag)`
  )

  fs.writeFileSync(OUTPUT_PATH, renderFile(entries))
  console.log(`Wrote ${OUTPUT_PATH}`)
}

main().catch(error => {
  console.error(error)
  process.exit(1)
})
